name: Update Submodules from Submodule Push

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Eventy
        run: |
          git clone https://x-access-token:${{ secrets.MAIN_REPO_TOKEN }}@github.com/Mattheo4427/Eventy.git
          cd Eventy
          git checkout main
          git submodule sync
          git submodule update --init --remote

      - name: Commit submodule updates
        run: |
          cd Eventy
          git add front back
          git diff-index --quiet HEAD || git commit -m "chore: update submodules after submodule push [skip ci]"

      - name: Push changes
        run: |
          cd Eventy
          git pull --rebase origin main
          git push origin main || echo "No changes to push"

      - name: Notify success
        run: echo "✅ Submodules updated in Eventy!"
